### ISSUE TITLE
change_dir "/usr/local/autotest/results/default" failed 

### ISSUE THREAD

**Issue by wuming0010** [autotest/autotest#1072]
rsync: change_dir "/usr/local/autotest/results/default" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
rsync: [Receiver] write error: Broken pipe (32)

**Comment by wuming0010** [comment]
04/27 06:02:44 ERROR|server_job:0551| Exception escaped control file, job aborting:
Traceback (most recent call last):
  File "/usr/local/autotest/server/server_job.py", line 543, in run
    self._execute_code(server_control_file, namespace)
  File "/usr/local/autotest/server/server_job.py", line 1004, in _execute_code
    execfile(code_file, namespace, namespace)
  File "/usr/local/autotest/results/5-debug_user/192.168.1.187/control.srv", line 11, in <module>
    job.parallel_simple(run_client, machines)
  File "/usr/local/autotest/server/server_job.py", line 446, in parallel_simple
    return_results=return_results)
  File "/usr/local/autotest/server/subcommand.py", line 96, in parallel_simple
    function(arg)
  File "/usr/local/autotest/results/5-debug_user/192.168.1.187/control.srv", line 8, in run_client
    at.run(control, host=host)
  File "/usr/local/autotest/server/autotest_remote.py", line 412, in run
    client_disconnect_timeout)
  File "/usr/local/autotest/server/autotest_remote.py", line 491, in _do_run
    client_disconnect_timeout=client_disconnect_timeout)
  File "/usr/local/autotest/server/autotest_remote.py", line 879, in execute_control
    logger, client_disconnect_timeout)
  File "/usr/local/autotest/server/autotest_remote.py", line 826, in execute_section
    raise err
AutotestRunError: client job was aborted

**Comment by wuming0010** [comment]
I don't know what happened, did I corrupt the autotest file?
