### ISSUE TITLE
Can't plot a Metrics plot

### ISSUE THREAD

**Issue by Stan-He** [autotest/autotest#911]
Hi, everyone
This is the first time I post a issue, when I am trying to plot a metrics graph on tko-graphing(web-site), I always get the error log below, I'am using python2.7.5+django1.5.11
------------------------------------------------------------------------------------------------------------
TypeError: integer argument expected, got float
Traceback (most recent call last):
  File "/usr/local/autotest/frontend/afe/json_rpc/serviceHandler.py", line 100, in dispatchRequest
    results['result'] = self.invokeServiceEndpoint(meth, args)
  File "/usr/local/autotest/frontend/afe/json_rpc/serviceHandler.py", line 135, in invokeServiceEndpoint
    def invokeServiceEndpoint(self, meth, args):
  File "/usr/local/autotest/frontend/afe/rpc_handler.py", line 114, in new_fn
    return f(*args, **keyword_args)
  File "/usr/local/autotest/frontend/tko/rpc_interface.py", line 255, in create_metrics_plot
    queries, plot, invert, normalize, drilldown_callback=drilldown_callback)
  File "/usr/local/autotest/frontend/tko/graphing_utils.py", line 646, in create_metrics_plot
  File "/usr/local/autotest/frontend/tko/graphing_utils.py", line 474, in _create_image_html
  File "/usr/local/autotest/frontend/tko/graphing_utils.py", line 448, in _create_png
    image_background = PIL.Image.new(image.mode, image.size,
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1844, in fromstring
    return frombytes(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1833, in frombytes
    im = new(mode, size)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1800, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float

**Comment by lmr** [comment]
This seems related to the fact that these interfaces are deprecated. Could you see if the patch

https://gist.github.com/lmr/2fcfd137dc4e155b2f21

Solves the issue?

**Comment by Stan-He** [comment]
No，still got the error log--- integer argument expected, got float
TypeError: integer argument expected, got float
Traceback (most recent call last):
  File "/usr/local/autotest/frontend/afe/json_rpc/serviceHandler.py", line 100, in dispatchRequest
    results['result'] = self.invokeServiceEndpoint(meth, args)
  File "/usr/local/autotest/frontend/afe/json_rpc/serviceHandler.py", line 136, in invokeServiceEndpoint
    return meth(*args)
  File "/usr/local/autotest/frontend/afe/rpc_handler.py", line 114, in new_fn
    return f(*args, **keyword_args)
  File "/usr/local/autotest/frontend/tko/rpc_interface.py", line 255, in create_metrics_plot
    queries, plot, invert, normalize, drilldown_callback=drilldown_callback)
  File "/usr/local/autotest/frontend/tko/graphing_utils.py", line 645, in create_metrics_plot
    return _create_image_html(figure, area_data, plot_info)
  File "/usr/local/autotest/frontend/tko/graphing_utils.py", line 473, in _create_image_html
    png, bbox = _create_png(figure)
  File "/usr/local/autotest/frontend/tko/graphing_utils.py", line 447, in _create_png
    image = PIL.Image.frombytes('RGB', size, image_as_string, 'raw', 'RGB', 0,1)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1833, in frombytes
    im = new(mode, size)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1800, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float
![qq 20150228132957](https://cloud.githubusercontent.com/assets/7049018/6425002/df28b1f8-bf4d-11e4-9a35-35e29875a96c.png)
