### ISSUE TITLE
Result Server Setup

### ISSUE THREAD

**Issue by omps** [autotest/autotest#932]
After doing the result server setup, getting the following error 

The variable which has been changed in global_config.ini file are

```
# Hostname to copy results to after job completion
results_host: hostname

# If you installed your results_host in a different location than the
# standard /local/0/autotest, this often will be blank
results_host_installation_directory:
hostname_username: autotest
```

```
06:48:38 ERROR| Exception escaping in scheduler
Traceback (most recent call last):
  File "/local/0/autotest/scheduler/monitor_db.py", line 279, in main
    main_without_exception_handling()
  File "/local/0/autotest/scheduler/monitor_db.py", line 255, in main_without_exception_handling
    server = status_server.StatusServer()
  File "/local/0/autotest/scheduler/status_server.py", line 104, in __init__
    StatusServerRequestHandler)
  File "/usr/lib64/python2.6/SocketServer.py", line 412, in __init__
    self.server_bind()
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.6/SocketServer.py", line 423, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/local/0/autotest/scheduler/autotest-scheduler", line 13, in <module>
    monitor_db.main()
  File "/local/0/autotest/scheduler/monitor_db.py", line 279, in main
    main_without_exception_handling()
  File "/local/0/autotest/scheduler/monitor_db.py", line 255, in main_without_exception_handling
    server = status_server.StatusServer()
  File "/local/0/autotest/scheduler/status_server.py", line 104, in __init__
    StatusServerRequestHandler)
  File "/usr/lib64/python2.6/SocketServer.py", line 412, in __init__
    self.server_bind()
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.6/SocketServer.py", line 423, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
```

I thought that it may be because of the running http server, but shutting down that as well did not solve the issue. Looks like something else.

**Comment by omps** [comment]
Fixed.. Looks like the result host was not setup with the keys for the autotest to communicate properly. Added the SSH keys and the error seems to have resolved.
