### ISSUE TITLE
Autotest Failing to install on fedora 22 - 32 bit version.

### ISSUE THREAD

**Issue by omps** [autotest/autotest#935]
Getting the below error while installing autotest on fedora 22.

```
13:09:16 INFO | Please stick with 1.5 for the time being
Traceback (most recent call last):
  File "/usr/local/autotest/installation_support/autotest-install-packages-deps", line 38, in <module>
    install_successful = software_manager.install_distro_packages(PKG_DEPS)
  File "/usr/local/autotest/client/shared/software_manager.py", line 828, in install_distro_packages
    if not software_manager.check_installed(pkg):
  File "/usr/local/autotest/client/shared/software_manager.py", line 139, in __getattr__
    self._init_on_demand()
  File "/usr/local/autotest/client/shared/software_manager.py", line 135, in _init_on_demand
    self.backend = backend()
  File "/usr/local/autotest/client/shared/software_manager.py", line 362, in __init__
    self.yum_base = yum.YumBase()
NameError: global name 'yum' is not defined
13:09:19 ERROR | Failed to install autotest packages dependencies

[root@localhost ~]# python
Python 2.7.9 (default, Apr 15 2015, 12:07:52) 
[GCC 5.0.0 20150319 (Red Hat 5.0.0-0.21)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.get_version()
'1.5'
>>> 
```

I feel the issue is more likely becuase of the yum being replaced with dnf
```
Yum command has been deprecated, redirecting to '/usr/bin/dnf install test'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'
```

**Comment by lmr** [comment]
Yes, the yum APIs are not available in Fedora 22, so `software_manager` needs to be updated.

**Comment by lmr** [comment]
@omps, I've submitted https://github.com/autotest/autotest/pull/936, that should fix this issue. Sorry for the inconvenience and thanks for the bug report. If possible, please test it and provide feedback on whether this actually fixes your problem.

**Comment by omps** [comment]
sorry I was not available for some time, I am checking and will update soon.
