### ISSUE TITLE
autotest-local fails due to directory copy failure

### ISSUE THREAD

**Issue by guilly314** [autotest/autotest#940]
Hello,
I'm really new with Autotest. I try to launch a local test (sleeptest) that fails miserably due to a folder copy error. I can not believe this is a bug in Autotest, there shall be something else, but I have no clue.
I tried on a fedora 21 VM (SELinux disabled) and an Ubuntu 14.10 VM, same failure for both.
I gave RW permission to the entire autotest tree for everybody. Same problem.
I tried being root (sudo), same problem.
Below are my traces... Thanks for your help.

[guillaume@localhost autotest-0.16.0]$ sudo ./client/autotest-local --verbose client/tests/sleeptest/
14:27:07 INFO | Writing results to /home/guillaume/Bureau/Autotest/autotest-0.16.0/client/results/default
14:27:07 DEBUG| Initializing the state engine
14:27:07 DEBUG| Persistent state client.steps now set to []
14:27:07 DEBUG| Persistent option harness now set to None
14:27:07 DEBUG| Persistent option harness_args now set to None
14:27:07 DEBUG| Selected harness: standalone
14:27:07 CRITI| JOB ERROR (autotest bug?): [Errno 21] Is a directory: '/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/tests/sleeptest'
Traceback (most recent call last):
  File "/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/job.py", line 1265, in runjob
    myjob = job(control=control, drop_caches=drop_caches, options=options)
  File "/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/job.py", line 120, in __init__
    self._pre_record_init(control, options)
  File "/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/job.py", line 200, in _pre_record_init
    self.harness = harness.select(_harness, self, _harness_args)
  File "/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/harness.py", line 92, in select
    harness_instance = getattr(harness_module, harness_name)(job, harness_args)
  File "/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/harness_standalone.py", line 41, in __init__
    shutil.copyfile(src, dest)
  File "/usr/lib64/python2.7/shutil.py", line 85, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: '/home/guillaume/Bureau/Autotest/autotest-0.16.0/client/tests/sleeptest'

**Comment by guilly314** [comment]
tried under root (sudo), same issue.
