### ISSUE TITLE
Error installing autotest server, autotest_web.tko_status mysql table missing

### ISSUE THREAD

**Issue by dmoraru** [autotest/autotest#957]
Hello,

I have an Ubuntu 14.04 LTS desktop. I used the script install-autotest-server.sh to install the auto test server, it ran fine until it reached line 414 where it invokes script autotest-database-turnkey 

13:12:01 INFO | Setting MySQL root password
13:12:01 INFO | Verifying MySQL root password
13:12:01 INFO | Creating MySQL databases for autotest
13:12:03 ERROR | Error creating MySQL database

Running this script with same params
sudo /usr/local/autotest/installation_support/autotest-database-turnkey -s --root-password=mypasswd -p mypasswd 

produces this error:

Traceback (most recent call last):
  File "/usr/local/autotest/installation_support/autotest-database-turnkey", line 201, in <module>
    result = app.run()
  File "/usr/local/autotest/installation_support/autotest-database-turnkey", line 174, in run
    django.core.management.execute_from_command_line(argv)
 ……..
django.db.utils.ProgrammingError: Problem installing fixture '/usr/local/autotest/frontend/tko/fixtures/initial_data.json': Could not load tko.Status(pk=1): (1146, "Table 'autotest_web.tko_status' doesn't exist")

Indeed, mysql has the autotest_web database, but there is no tko_status table.

Also, the steps to setup MySQL manually are out of sync with the script and don’t contain much info. They contain a command to create database tko, that is also not created by the automated script.
http://autotest.readthedocs.org/en/latest/main/sysadmin/AutotestServerInstallDatabase.html

Can you help?

Thanks
Danut

**Comment by dmoraru** [comment]
install-autotest-server-08-10-2015-13-10-32.log
13:10:32 INFO | Installing the Autotest server
13:10:32 INFO | A log of operation is kept in /tmp/install-autotest-server-08-07-2015-13-10-32.log
13:10:32 INFO | Install started at: Fri Aug 7 13:10:32 PDT 2015
13:10:32 INFO | /usr/local free 25G
13:10:32 INFO | /var free 25G
13:10:32 INFO | Installing basic packages
Reading package lists...
Building dependency tree...
Reading state information...
makepasswd is already the newest version.
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
13:10:32 INFO | Creating autotest user
13:10:32 INFO | Adding user autotest
13:10:32 INFO | Installing autotest
13:10:32 INFO | Cloning autotest repo git://github.com/autotest/autotest.git, branch master in /usr/local/autotest
13:10:52 INFO | Initializing and updating tests to the latest master
13:11:14 INFO | Setting proper permissions for the autotest directory
13:11:14 INFO | Installing packages dependencies
13:11:14 INFO | Please note that autotest is compatible with Django 1.5
13:11:14 INFO | If your distro/local install is different, you WILL have problems
13:11:14 INFO | Please stick with 1.5 for the time being
13:11:16 INFO | No specific distro release package list
13:11:16 INFO | Installing packages "apache2-mpm-prefork git libapache2-mod-wsgi makepasswd mysql-server openjdk-7-jre-headless python-crypto python-django python-django-south python-httplib2 python-imaging python-matplotlib python-mysqldb python-numpy python-paramiko python-setuptools python-simplejson python-psutil unzip wget protobuf-compiler python-protobuf pylint"
13:11:56 ERROR| [stderr] mysql start/running, process 10181
13:11:58 INFO | Enabling MySQL server on boot
 Adding system startup for /etc/init.d/mysql ...
   /etc/rc0.d/K20mysql -> ../init.d/mysql
   /etc/rc1.d/K20mysql -> ../init.d/mysql
   /etc/rc6.d/K20mysql -> ../init.d/mysql
   /etc/rc2.d/S20mysql -> ../init.d/mysql
   /etc/rc3.d/S20mysql -> ../init.d/mysql
   /etc/rc4.d/S20mysql -> ../init.d/mysql
   /etc/rc5.d/S20mysql -> ../init.d/mysql
13:11:58 INFO | Re-starting MySQL server
mysql stop/waiting
mysql start/running, process 10500
13:12:01 INFO | Setting MySQL root password
13:12:01 INFO | Verifying MySQL root password
13:12:01 INFO | Creating MySQL databases for autotest
13:12:03 ERROR | Error creating MySQL database

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| autotest_web       |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.00 sec)



mysql> use autotest_web
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+------------------------------------------------+
| Tables_in_autotest_web                         |
+------------------------------------------------+
| afe_aborted_host_queue_entries                 |
| afe_acl_groups                                 |
| afe_acl_groups_hosts                           |
| afe_acl_groups_users                           |
| afe_atomic_groups                              |
| afe_autotests                                  |
| afe_autotests_dependency_labels                |
| afe_drone_sets                                 |
| afe_drone_sets_drones                          |
| afe_drones                                     |
| afe_host_attributes                            |
| afe_host_queue_entries                         |
| afe_hosts                                      |
| afe_hosts_labels                               |
| afe_ineligible_host_queues                     |
| afe_job_keyvals                                |
| afe_jobs                                       |
| afe_jobs_dependency_labels                     |
| afe_kernels                                    |
| afe_labels                                     |
| afe_parameterized_job_kernels                  |
| afe_parameterized_job_parameters               |
| afe_parameterized_job_profiler_parameters      |
| afe_parameterized_jobs                         |
| afe_parameterized_jobs_profilers               |
| afe_profilers                                  |
| afe_recurring_run                              |
| afe_special_tasks                              |
| afe_test_parameters                            |
| afe_users                                      |
| auth_group                                     |
| auth_group_permissions                         |
| auth_permission                                |
| auth_user                                      |
| auth_user_groups                               |
| auth_user_user_permissions                     |
| django_admin_log                               |
| django_content_type                            |
| django_session                                 |
| django_site                                    |
| linux_distro                                   |
| linux_distro_available_software_components     |
| migrate_info                                   |
| software_component                             |
| software_component_arch                        |
| software_component_kind                        |
| south_migrationhistory                         |
| test_environment                               |
| test_environment_installed_software_components |
+------------------------------------------------+
49 rows in set (0.00 sec)

**Comment by wuyeliang** [comment]
Excuse me, have you solved this problem? How to solve it? Thank you
