### ISSUE TITLE
Getting issue with autotest scheduler

### ISSUE THREAD

**Issue by omps** [autotest/autotest#958]
Hi,

getting this error, can you please guide me.

 12:39:52 ERROR| Uncaught exception, terminating scheduler
Traceback (most recent call last):
  File "/local/0/autotest/scheduler/monitor_db.py", line 259, in main_without_exception_handling
    initialize()
  File "/local/0/autotest/scheduler/monitor_db.py", line 180, in initialize
    _db.connect(db_type='django')
  File "/local/0/autotest/database_legacy/database_connection.py", line 242, in connect
    self._connect_backend(try_reconnecting)
  File "/local/0/autotest/database_legacy/database_connection.py", line 216, in _connect_backend
    db_name=self.db_name)
  File "/local/0/autotest/database_legacy/database_connection.py", line 127, in connect
    self._cursor = self._connection.cursor()
  File "/usr/lib/python2.6/site-packages/django/db/backends/__init__.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user 'autotest'@'localhost' (using password: YES)")
localhost.localdomain - - [14/Aug/2015 12:39:52] "GET http://localhost:13467 HTTP/1.0" 200 -
12:39:52 ERROR| Exception escaping in scheduler
Traceback (most recent call last):
  File "/local/0/autotest/scheduler/monitor_db.py", line 279, in main
    main_without_exception_handling()
  File "/local/0/autotest/scheduler/monitor_db.py", line 272, in main_without_exception_handling
    _drone_manager.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/local/0/autotest/scheduler/autotest-scheduler", line 13, in <module>
    monitor_db.main()
  File "/local/0/autotest/scheduler/monitor_db.py", line 279, in main
    main_without_exception_handling()
  File "/local/0/autotest/scheduler/monitor_db.py", line 272, in main_without_exception_handling
    _drone_manager.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

**Comment by lmr** [comment]
It seems you have set incorrect password credentials. You have to check if the values

# DB user
user: autotest

# DB password. You must set a different password than the default
password: please_set_this_password

In your `global_config.ini` file match the values actually set in your MySQL database.

**Comment by omps** [comment]
Thanks LMR, actually i checked the branch and i was on master branch of autotest, which for sure doesn't have the configuration for the particular configuration. doing a checkout to the specific commit branch did work.
