### ISSUE TITLE
jobs cannot run，permission denied

### ISSUE THREAD

**Issue by Tiny2009** [autotest/autotest#977]
I have installed autotest using the install script， but all my jobs in the job list are owned by debug_user,not root, and all the jobs are failed. bellow is the error info. so how can I change the jobs owener to root ,not debug_user

09/24 09:37:14 ERROR| traceback:0013| Traceback (most recent call last):
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/autoserv.py", line 153, in run_autoserv
09/24 09:37:14 ERROR| traceback:0013|     job.repair(host_protection)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/server_job.py", line 363, in repair
09/24 09:37:14 ERROR| traceback:0013|     self._execute_code(REPAIR_CONTROL_FILE, namespace, protect=False)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/server_job.py", line 997, in _execute_code
09/24 09:37:14 ERROR| traceback:0013|     execfile(code_file, namespace, namespace)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/control_segments/repair", line 27, in <module>
09/24 09:37:14 ERROR| traceback:0013|     job.parallel_simple(repair, machines)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/server_job.py", line 439, in parallel_simple
09/24 09:37:14 ERROR| traceback:0013|     return_results=return_results)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/subcommand.py", line 97, in parallel_simple
09/24 09:37:14 ERROR| traceback:0013|     function(arg)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/control_segments/repair", line 19, in repair
09/24 09:37:14 ERROR| traceback:0013|     _call_repair(machine)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/server/control_segments/repair", line 14, in _call_repair
09/24 09:37:14 ERROR| traceback:0013|     host.repair_with_protection(level)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/client/shared/hosts/base_classes.py", line 432, in repair_with_protection
09/24 09:37:14 ERROR| traceback:0013|     self.repair_full()
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/client/shared/hosts/base_classes.py", line 389, in repair_full
09/24 09:37:14 ERROR| traceback:0013|     self.repair_software_only()
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/client/shared/hosts/base_classes.py", line 383, in repair_software_only
09/24 09:37:14 ERROR| traceback:0013|     self._call_repair_func(err, self.machine_install)
09/24 09:37:14 ERROR| traceback:0013|   File "/usr/local/autotest/client/shared/hosts/base_classes.py", line 338, in _call_repair_func
09/24 09:37:14 ERROR| traceback:0013|     raise err
09/24 09:37:14 ERROR| traceback:0013| AutoservSshPingHostError: command execution error
09/24 09:37:14 ERROR| traceback:0013| * Command: 
09/24 09:37:14 ERROR| traceback:0013|     /usr/bin/ssh -a -x  -o ControlPath=/tmp/_autotmp_X97bYMssh-master/socket
09/24 09:37:14 ERROR| traceback:0013|     -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/tmpN48RzS -o
09/24 09:37:14 ERROR| traceback:0013|     BatchMode=yes -o ConnectTimeout=60 -o ServerAliveInterval=300 -l root -p
09/24 09:37:14 ERROR| traceback:0013|     22 172.27.255.62 " true"
09/24 09:37:14 ERROR| traceback:0013| Exit status: 255
09/24 09:37:14 ERROR| traceback:0013| Duration: 0.11533498764
09/24 09:37:14 ERROR| traceback:0013| 
09/24 09:37:14 ERROR| traceback:0013| stderr:
09/24 09:37:14 ERROR| traceback:0013| Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by lmr** [comment]
1) The fact that the jobs appear as `debug_user` doesn't interfere in the user that's actually used to run autotest. As you can see the user that runs the ssh command is root: `BatchMode=yes -o ConnectTimeout=60 -o ServerAliveInterval=300 -l root -p`.
2) What you have here is that the root user can't ssh into the client machine, as the command output demonstrates: ` Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).`.
