### ISSUE TITLE
Web frontend not showing all test cases for client

### ISSUE THREAD

**Issue by toralMevada** [autotest/autotest#979]
While creating new job, I am not seeing sleeptest for client. 
I am not seeing full list of test cases which are present in autotest/client/test.

Any suggestions?

**Comment by lmr** [comment]
`utils/test_importer.py -a` should be the command that would let you import all available tests

**Comment by toralMevada** [comment]
@lmr 
Thanks, but I am unable to run the script successfully. 

toral@toral:/usr/local/autotest$ python utils/test_importer.py --add-all
11:39:41 INFO | Scanning /usr/local/autotest/server/tests
11:39:41 INFO | Processing server/tests/netperf2/control.srv
11:39:41 INFO | Processing server/tests/iperf/control.srv
11:39:41 INFO | Processing server/tests/multihost_migration_mix/control.srv
11:39:41 INFO | Processing server/tests/iperf/control.stress.srv
11:39:41 INFO | Processing server/tests/sleeptest/control
11:39:42 INFO | Processing server/tests/cleanup_test/control
11:39:42 INFO | Processing server/tests/reinstall/control
Traceback (most recent call last):
  File "utils/test_importer.py", line 591, in <module>
    main(sys.argv)
  File "utils/test_importer.py", line 570, in main
    options.add_experimental)
  File "utils/test_importer.py", line 87, in update_all
    autotest_dir=autotest_dir)
  File "utils/test_importer.py", line 235, in update_tests_in_db
    path=test.replace(autotest_dir, '').lstrip('/'))[0]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 146, in get_or_create
    return self.get_query_set().get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 487, in get_or_create
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 477, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1661, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 122, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1062, "Duplicate entry '' for key 'name'")
toral@toral:/usr/local/autotest$

**Comment by lmr** [comment]
Hmm, that error usually happens when the tests are already in the database. Then I'm not sure why the tests aren't being listed.

**Comment by toralMevada** [comment]
Even following add all test after clearing all not working and giving similar error. 

$ python utils/test_importer.py --db-clean-tests
$ python utils/test_importer.py --db-clear-all-tests
$ python utils/test_importer.py --add-all

toral@toral:/usr/local/autotest$ python utils/test_importer.py --add-all
12:24:58 INFO | Scanning /usr/local/autotest/server/tests
12:24:58 INFO | Processing server/tests/netperf2/control.srv
12:24:58 INFO | Processing server/tests/iperf/control.srv
12:24:58 INFO | Processing server/tests/multihost_migration_mix/control.srv
12:24:58 INFO | Processing server/tests/iperf/control.stress.srv
12:24:58 INFO | Processing server/tests/sleeptest/control
12:24:59 INFO | Processing server/tests/cleanup_test/control
12:24:59 INFO | Processing server/tests/reinstall/control
12:24:59 INFO | Processing server/tests/verify_test/control
12:24:59 INFO | Processing server/tests/multihost_migration/control.srv
12:24:59 INFO | Processing server/tests/barriertest_2client/control.srv
12:24:59 INFO | Processing server/tests/netpipe/control.stress.srv
12:24:59 INFO | Processing server/tests/netpipe/control.srv
12:24:59 INFO | Processing server/tests/netperf2/control.stress.srv
12:24:59 INFO | Scanning /usr/local/autotest/client/tests
12:24:59 WARNI| Skipping /usr/local/autotest/client/tests/virt/virttest/libvirt_xml/devices/controller.py
WARNING: Not all required control variables were specified in /usr/local/autotest/client/tests/virt/virttest/libvirt_xml/devices/controller.py.  Please define name, author, doc, test_type, test_category, test_class, time.
12:24:59 WARNI| Skipping /usr/local/autotest/client/tests/docker/control
WARNING: Not all required control variables were specified in /usr/local/autotest/client/tests/docker/control.  Please define test_category, test_class.
12:24:59 WARNI| Skipping /usr/local/autotest/client/tests/docker/control.example
WARNING: Not all required control variables were specified in /usr/local/autotest/client/tests/docker/control.example.  Please define test_category, test_class.
12:24:59 WARNI| Skipping /usr/local/autotest/client/tests/docker/config_defaults/control.ini
Error parsing /usr/local/autotest/client/tests/docker/config_defaults/control.ini because invalid syntax (line 12)
12:24:59 WARNI| Skipping /usr/local/autotest/client/tests/regression/control
WARNING: Not all required control variables were specified in /usr/local/autotest/client/tests/regression/control.  Please define doc.
12:24:59 INFO | Processing client/tests/hackbench/control
12:24:59 INFO | Processing client/tests/error_test_bug/control
12:25:00 INFO | Processing client/tests/ebizzy/control
12:25:00 INFO | Processing client/tests/dma_memtest/control
12:25:00 INFO | Processing client/tests/aio_dio_bugs/control~
12:25:00 INFO | Processing client/tests/kernelbuild/control
12:25:00 INFO | Processing client/tests/spew/control
12:25:00 INFO | Processing client/tests/stress/control
12:25:00 INFO | Processing client/tests/libvirt_tck/control
12:25:00 INFO | Processing client/tests/tsc/control
12:25:00 INFO | Processing client/tests/aio_dio_bugs/control
Traceback (most recent call last):
  File "utils/test_importer.py", line 591, in <module>
    main(sys.argv)
  File "utils/test_importer.py", line 570, in main
    options.add_experimental)
  File "utils/test_importer.py", line 87, in update_all
    autotest_dir=autotest_dir)
  File "utils/test_importer.py", line 261, in update_tests_in_db
    _log_or_execute(repr(new_test), new_test.save)
  File "utils/test_importer.py", line 418, in _log_or_execute
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 626, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 591, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1014, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 122, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1062, "Duplicate entry 'aio dio bugs' for key 'name'")
