### ISSUE TITLE
./autoserv example.control not executing. 

### ISSUE THREAD

**Issue by toralMevada** [autotest/autotest#980]
./autoserve did not run to execute a control file as explained in below link.  
http://autotest.readthedocs.org/en/latest/main/remote/Autoserv.html#control-files

CLI:
toral@toral:/usr/local/autotest$ python server/autoserv.py mytest.control
toral@toral:/usr/local/autotest$ 

May be because it is missing the entry point. (entry point is removed in previous commit on 21 Jan 2014 - https://github.com/autotest/autotest/commit/2e952c1e51067b0b4c6e41aebde7518127f7f8d7)

Could you please guide how to run the control file using autoserv script?

**Comment by lmr** [comment]
That's because that entry point has been renamed:

    server/autotest-remote 
    #!/usr/bin/python -u
    """
    Run an control file using the remote engine.

    @copyright: 2007-2008 Martin J. Bligh <mbligh@google.com>, Google Inc.
    @license: GPL v2
    """

    try:
        import autotest.common as common
    except ImportError:
        import common
    from autotest.server import autoserv


    if __name__ == '__main__':
        autoserv.main()

The documentation needs update. If you could send a patch fixing that instance, I'd be grateful. Thanks!

**Comment by lmr** [comment]
Double checking, you should use server/autotest-remote instead.

**Comment by CentUser** [comment]
@lmr I tried with the instructions here, and got the following call trace:

with the example provided by doc :http://autotest.readthedocs.io/en/latest/main/remote/Autoserv.html#

remote_host= hosts.SSHHost("172.20.0.106")

at= autotest.Autotest()
at.get("/var/local/autotest/client")
at.install(remote_host)

control_file= """
job.profilers.add("oprofile", events= ["CPU_CLK_UNHALTED:8000"])
job.run_test("linus_stress")
"""

results_dir= "job_results"

at.run(control_file, results_dir, remote_host)


11:39:05 INFO | Results placed in /usr/local/autotest/results.2018-07-17-11.39.05
11:39:05 INFO | conmux directory set to: <autotest.client.shared.base_job.job_directory object at 0x7f85bf351990>
11:39:05 INFO | Processing control file
11:39:05 ERROR| Exception escaped control file, job aborting:
Traceback (most recent call last):
  File "/usr/local/autotest/server/server_job.py", line 543, in run
    self._execute_code(server_control_file, namespace)
  File "/usr/local/autotest/server/server_job.py", line 1004, in _execute_code
    execfile(code_file, namespace, namespace)
  File "/usr/local/autotest/results.2018-07-17-11.39.05/control.srv", line 3, in <module>
    at= autotest.Autotest()
NameError: name 'autotest' is not defined
11:39:05 INFO | INFO	----	----	timestamp=1531827545	job_abort_reason=name 'autotest' is not defined	localtime=Jul 17 11:39:05	name 'autotest' is not defined
11:39:05 ERROR| Traceback (most recent call last):
11:39:05 ERROR|   File "/usr/local/autotest/server/autoserv.py", line 158, in run_autoserv
11:39:05 ERROR|     only_collect_crashinfo=collect_crashinfo)
11:39:05 ERROR|   File "/usr/local/autotest/server/server_job.py", line 543, in run
11:39:05 ERROR|     self._execute_code(server_control_file, namespace)
11:39:05 ERROR|   File "/usr/local/autotest/server/server_job.py", line 1004, in _execute_code
11:39:05 ERROR|     execfile(code_file, namespace, namespace)
11:39:05 ERROR|   File "/usr/local/autotest/results.2018-07-17-11.39.05/control.srv", line 3, in <module>
11:39:05 ERROR|     at= autotest.Autotest()
11:39:05 ERROR| NameError: name 'autotest' is not defined


I think, there should be another one change in the name autotest...
